package studio.sculk.data

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import studio.sculk.annotation.SculkInternal
import studio.sculk.config.SculkConfig
import java.io.File
import java.util.logging.Logger

/**
 * The shipped `storage.yml` is generated by the config system, so it is also read back by it. These
 * cover the seam between the two, which is where a file that generates cleanly can still fail to
 * load on the next boot.
 */
@OptIn(SculkInternal::class)
class StorageSettingsTest {
    @TempDir
    lateinit var folder: File

    private fun config(env: Map<String, String> = emptyMap()) = SculkConfig(folder, Logger.getLogger("test")) { env[it] }

    @Test
    fun `the generated storage file loads on the second boot as well as the first`() {
        // `password` defaults to an environment placeholder, so the generated file is the one input
        // this config is guaranteed to be given. It has to survive its own round trip.
        config().load<StorageSettings>().getOrThrow()

        val second = config().load<StorageSettings>()

        assertTrue(second.isSuccess, "the file the first boot wrote must still load, got: $second")
        assertEquals("", second.getOrThrow().remote.password, "an unset DB_PASSWORD means no password, not a broken file")
    }

    @Test
    fun `the password comes from the environment when one is set`() {
        config().load<StorageSettings>().getOrThrow()

        val loaded = config(mapOf("DB_PASSWORD" to "hunter2")).load<StorageSettings>().getOrThrow()

        assertEquals("hunter2", loaded.remote.password)
    }

    @Test
    fun `the shipped defaults break none of their own constraints`() {
        assertEquals(emptyList<String>(), config().violations<StorageSettings>())
    }
}
