name: CrateSystem
version: '${version}'
main: studio.sculk.example.CrateSystemPlugin
description: Sculk Studio crate system recipe example
api-version: '26.1.2'
authors:
  - SculkStudios
folia-supported: true
