name: DaisyTracker

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DaisyCatTs/DaisyTracker@v2
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
